def display_info(stdscr, user):
    stdscr.clear()
    stdscr.addstr(0, 0, f"Login: {user.login}")
    stdscr.addstr(1, 0, f"Name: {user.name}")
    stdscr.addstr(2, 0, f"Public Repositories: {user.public_repos}")
    stdscr.addstr(3, 0, f"Followers: {user.followers}")
    stdscr.addstr(4, 0, f"Following: {user.following}")
    stdscr.addstr(6, 0, "Press any key to return to the menu...")
    stdscr.refresh()
    stdscr.getch()
